name: CI/CD Pipeline

# Условия запуска workflow
on:
  push:
    branches:
      - main  # Запуск при коммите в ветку main
  pull_request:
    branches:
      - main  # Запуск при создании pull request в ветку main

# Задачи, выполняемые в workflow
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Получение кода из репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Установка Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Установка зависимостей
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Запуск тестов
      - name: Run tests
        run: |
          python -m pytest

      # Сборка проекта
      - name: Build project
        run: |
          echo "Building project..."

      # Уведомление о завершении
      - name: Notify completion
        run: |
          echo "CI/CD pipeline completed successfully!"